"use client";

import { CalendarDays, Check, Clock3, Copy, MapPin, Shield, UsersRound } from "lucide-react";
import { useParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { getSupabase } from "@/lib/supabase";
import { formatLongDate, shortTime } from "@/lib/format";
import type { AttendanceStatus, Player, TeamEvent } from "@/lib/types";

type AttendanceRow={id:string;player_id:string;status:AttendanceStatus;reason:string|null};
type NominationRow={id:string;player_id:string;status:"selected"|"starting"|"bench"};
const statuses:{value:AttendanceStatus;label:string}[]=[{value:"available",label:"Dabei"},{value:"unavailable",label:"Abgesagt"},{value:"excused",label:"Entschuldigt"},{value:"injured",label:"Verletzt"},{value:"pending",label:"Offen"}];

export default function EventDetailPage(){
  const params=useParams<{id:string}>(); const id=params.id;
  const [event,setEvent]=useState<TeamEvent|null>(null); const [players,setPlayers]=useState<Player[]>([]); const [attendance,setAttendance]=useState<AttendanceRow[]>([]); const [nominations,setNominations]=useState<NominationRow[]>([]); const [copied,setCopied]=useState(false);
  async function load(){const supabase=getSupabase();if(!supabase)return;const {data:eventData}=await supabase.from("events").select("*").eq("id",id).single();if(!eventData)return;setEvent(eventData as TeamEvent);const [playerResult,attendanceResult,nominationResult]=await Promise.all([supabase.from("players").select("*").eq("team_id",eventData.team_id).eq("active",true).order("last_name"),supabase.from("attendance").select("*").eq("event_id",id),supabase.from("nominations").select("*").eq("event_id",id)]);setPlayers((playerResult.data??[]) as Player[]);setAttendance((attendanceResult.data??[]) as AttendanceRow[]);setNominations((nominationResult.data??[]) as NominationRow[])}
  useEffect(()=>{load();},[id]);
  const summary=useMemo(()=>({available:attendance.filter(a=>a.status==="available").length,unavailable:attendance.filter(a=>["unavailable","excused","injured"].includes(a.status)).length,pending:Math.max(players.length-attendance.filter(a=>a.status!=="pending").length,0)}),[attendance,players.length]);
  async function setAttendanceStatus(playerId:string,status:AttendanceStatus){const supabase=getSupabase();if(!supabase)return;const existing=attendance.find(row=>row.player_id===playerId);if(existing){await supabase.from("attendance").update({status,responded_at:new Date().toISOString()}).eq("id",existing.id);setAttendance(rows=>rows.map(row=>row.id===existing.id?{...row,status}:row))}else{const {data}=await supabase.from("attendance").insert({event_id:id,player_id:playerId,status,responded_at:new Date().toISOString()}).select("*").single();if(data)setAttendance(rows=>[...rows,data as AttendanceRow])}}
  async function toggleNomination(playerId:string){const supabase=getSupabase();if(!supabase)return;const existing=nominations.find(row=>row.player_id===playerId);if(existing){await supabase.from("nominations").delete().eq("id",existing.id);setNominations(rows=>rows.filter(row=>row.id!==existing.id))}else{const {data}=await supabase.from("nominations").insert({event_id:id,player_id:playerId,status:"selected"}).select("*").single();if(data)setNominations(rows=>[...rows,data as NominationRow])}}
  async function copyMessage(){if(!event)return;const selected=players.filter(p=>nominations.some(n=>n.player_id===p.id)).map(p=>`${p.first_name} ${p.last_name}`).join(", ");const text=`${event.type==="match"?"Spiel":"Training"}: ${event.title}\n${formatLongDate(event.event_date)} · ${shortTime(event.start_time)} Uhr\nTreffpunkt: ${shortTime(event.meeting_time)} Uhr${event.location?`\nOrt: ${event.location}`:""}${selected?`\n\nKader: ${selected}`:""}${event.notes?`\n\nHinweis: ${event.notes}`:""}`;await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1600)}
  if(!event)return <div className="empty">Termin wird geladen …</div>;
  return <><header className="page-head"><div><p className="eyebrow">{event.type==="match"?event.competition||"Spieltag":"Training"}</p><h1>{event.title}</h1><p className="muted">{formatLongDate(event.event_date)}</p></div><button className="button button-ghost" onClick={copyMessage}><Copy size={16}/>{copied?"Kopiert":"WhatsApp-Text kopieren"}</button></header>
    <section className="grid-kpis"><article className="kpi"><span className="kpi-icon"><Clock3 size={20}/></span><div><strong>{shortTime(event.meeting_time)}</strong><span>Treffpunkt</span></div></article><article className="kpi"><span className="kpi-icon"><CalendarDays size={20}/></span><div><strong>{shortTime(event.start_time)}</strong><span>{event.type==="match"?"Anstoß":"Beginn"}</span></div></article><article className="kpi"><span className="kpi-icon"><Check size={20}/></span><div><strong>{summary.available}</strong><span>Zusagen</span></div></article><article className="kpi"><span className="kpi-icon"><UsersRound size={20}/></span><div><strong>{nominations.length}</strong><span>Nominiert</span></div></article></section>
    <div className="dashboard-grid"><section className="card"><div className="card-head"><div><p className="eyebrow">Rückmeldungen</p><h2>Anwesenheit</h2></div><span className="badge badge-amber">{summary.pending} offen</span></div><div className="stack">{players.map(player=>{const status=attendance.find(a=>a.player_id===player.id)?.status??"pending";return <div key={player.id} style={{padding:"12px 0",borderTop:"1px solid #edf0ec"}}><div className="player-name" style={{marginBottom:9}}><span className="number">{player.shirt_number??"–"}</span>{player.first_name} {player.last_name}</div><div className="status-grid">{statuses.map(item=><button type="button" className={`status-button ${status===item.value?"active":""}`} onClick={()=>setAttendanceStatus(player.id,item.value)} key={item.value}>{item.label}</button>)}</div></div>})}</div></section>
      <aside className="stack"><section className="card"><div className="card-head"><div><p className="eyebrow">Details</p><h2>Termininfo</h2></div>{event.type==="match"?<Shield size={20}/>:<CalendarDays size={20}/>}</div><div className="match-meta" style={{color:"var(--muted)"}}>{event.location&&<span><MapPin size={15}/>{event.location}</span>}{event.notes&&<span>{event.notes}</span>}</div></section>{event.type==="match"&&<section className="card"><div className="card-head"><div><p className="eyebrow">Spieltagskader</p><h2>{nominations.length} nominiert</h2></div></div><div className="stack">{players.map(player=>{const selected=nominations.some(n=>n.player_id===player.id);return <button type="button" className="nomination-player" onClick={()=>toggleNomination(player.id)} key={player.id}><span><strong>{player.first_name} {player.last_name}</strong><span>{player.primary_position??"–"}</span></span><span className={`badge ${selected?"badge-green":"badge-gray"}`}>{selected?"Dabei":"+ Kader"}</span></button>})}</div></section>}</aside></div>
  </>;
}
